/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mahoahiendai;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Base64;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MaHoaFrame extends javax.swing.JFrame {

    /**
     * Creates new form MaHoaFrame
     */
    byte[] fileData = null;
    String filePath = null;
    String filePath2 = null;
    JFileChooser chooser = new JFileChooser();
    String fileName = null;
    String duoiFile = null;
    String tenFileMaHoa = null;
    String duongDanMoi = null;
    public MaHoaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRC4Key = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRC4PT = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRC4CT = new javax.swing.JTextArea();
        btnFile = new javax.swing.JButton();
        btnEncryp = new javax.swing.JButton();
        btnDecryp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFile1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtA5PT = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtA5CT = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtA5Key = new javax.swing.JTextField();
        btnA5Decryption = new javax.swing.JButton();
        btnA5Encryption = new javax.swing.JButton();
        btnA5File = new javax.swing.JButton();
        btnA5File1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Key:");

        txtRC4PT.setColumns(20);
        txtRC4PT.setRows(5);
        jScrollPane1.setViewportView(txtRC4PT);

        txtRC4CT.setColumns(20);
        txtRC4CT.setRows(5);
        jScrollPane2.setViewportView(txtRC4CT);

        btnFile.setText("Select File Encry");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        btnEncryp.setText("Encryption");
        btnEncryp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncrypActionPerformed(evt);
            }
        });

        btnDecryp.setText("Decryption");
        btnDecryp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecrypActionPerformed(evt);
            }
        });

        jLabel2.setText("Plain Text:");

        jLabel3.setText("Cipher Text:");

        btnFile1.setText("Select File Decry");
        btnFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFile1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(478, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEncryp)
                                            .addComponent(btnDecryp))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnFile, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnFile1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRC4Key, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtRC4Key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEncryp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFile))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDecryp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFile1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("RC4", jPanel1);

        jLabel4.setText("Plain Text:");

        jLabel5.setText("Cipher Text");

        txtA5PT.setColumns(20);
        txtA5PT.setRows(5);
        jScrollPane3.setViewportView(txtA5PT);

        txtA5CT.setColumns(20);
        txtA5CT.setRows(5);
        jScrollPane4.setViewportView(txtA5CT);

        jLabel6.setText("Key:");

        btnA5Decryption.setText("Decryption");
        btnA5Decryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA5DecryptionActionPerformed(evt);
            }
        });

        btnA5Encryption.setText("Encryption");
        btnA5Encryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA5EncryptionActionPerformed(evt);
            }
        });

        btnA5File.setText("Select File Encry");
        btnA5File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA5FileActionPerformed(evt);
            }
        });

        btnA5File1.setText("Select File Decry");
        btnA5File1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA5File1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtA5Key, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnA5Encryption)
                                .addComponent(btnA5Decryption)))
                        .addComponent(btnA5File, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnA5File1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtA5Key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnA5Encryption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnA5File)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnA5Decryption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnA5File1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("A5", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            filePath = chooser.getSelectedFile().getAbsolutePath();
            try {
                // đọc byte[]
                fileData = xulyFile.docFile(filePath);
                // convert sang Base64 để hiển thị an toàn (mọi loại file)
                String hienThi = Base64.getEncoder().encodeToString(fileData);
                // đưa vào text field
                txtRC4PT.setText(hienThi);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi đọc file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnFileActionPerformed

    private void btnEncrypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncrypActionPerformed
        if (fileData == null) {
        JOptionPane.showMessageDialog(this, "Bạn chưa chọn file!");
        return;
        }
        try {
            duoiFile = filePath.substring(filePath.lastIndexOf("."));
            // mã hóa RC4
            RC4 rc4ForFile = new RC4(txtRC4Key.getText().getBytes("UTF-8"));
            RC4 rc4ForName = new RC4(txtRC4Key.getText().getBytes("UTF-8"));
            byte[] encryptedFile = rc4ForFile.maHoa(fileData);
            xulyFile.ghiFile(filePath, encryptedFile);
            String fileMoi = filePath.replace(".rc4", "");
            //mã hóa tên file
            byte[] encryptedName = rc4ForName.maHoa(fileMoi.getBytes());
            // đỗi sang Base64 để dùng làm tên file hợp lệ
            tenFileMaHoa = Base64.getUrlEncoder().encodeToString(encryptedName);
            fileName = tenFileMaHoa+duoiFile;
            Path cu = Paths.get(filePath);
            String thuMuc = cu.getParent().toString();
            duongDanMoi = thuMuc + "/" + fileName;
            xulyFile.doiTenFile(filePath, duongDanMoi);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi mã hóa: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEncrypActionPerformed

    private void btnDecrypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecrypActionPerformed
        if (fileData == null) {
        JOptionPane.showMessageDialog(this, "Bạn chưa chọn file!");
        return;
        }
        try {
            // mã hóa RC4
            RC4 rc4 = new RC4(txtRC4Key.getText().getBytes("UTF-8"));
            RC4 rc4ForName = new RC4(txtRC4Key.getText().getBytes("UTF-8"));
            byte[] encrypted = rc4.giaiMa(fileData);
            // hiển thị kết quả dạng Base64
            String ketQua = Base64.getEncoder().encodeToString(encrypted);
            txtRC4PT.setText(ketQua);
            xulyFile.ghiFile(filePath2, encrypted);
            //String fileMoi = filePath.replace(".rc4", "");
            String tenMaHoa = xulyFile.layTenFile(filePath2);
            String tenBase64 = xulyFile.xoaDuoiFile(tenMaHoa);
            byte[] nameBytesEncrypted = Base64.getUrlDecoder().decode(tenBase64);
            byte[] nameBytesDecrypted = rc4ForName.maHoa(nameBytesEncrypted);
            String tenGoc = new String(nameBytesDecrypted, StandardCharsets.UTF_8);
            xulyFile.doiTenFile(filePath2, tenGoc);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi giải mã: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDecrypActionPerformed

    private void btnA5FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5FileActionPerformed
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            filePath = chooser.getSelectedFile().getAbsolutePath();
            try {
                // đọc byte[]
                fileData = xulyFile.docFile(filePath);
                // convert sang Base64 để hiển thị an toàn (mọi loại file)
                String hienThi = Base64.getEncoder().encodeToString(fileData);
                // đưa vào text field
                duoiFile = filePath.substring(filePath.lastIndexOf("."));
                txtA5PT.setText(hienThi);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi đọc file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnA5FileActionPerformed

    private void btnA5DecryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5DecryptionActionPerformed
        try {
        byte[] data = xulyFile.docFile(filePath2);
        String keyText = txtA5Key.getText();
        if (keyText == null || keyText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập key!");
            return;
        }
        int[] key = new int[keyText.length()];
        for (int i = 0; i < keyText.length(); i++) key[i] = keyText.charAt(i) & 1;
        A5 a5Data = new A5(key);
        int[] bits = A5.doiInt(data);
        int[] keystream = a5Data.maHoa(bits.length);
        for (int i = 0; i < bits.length; i++) bits[i] ^= keystream[i];
        byte[] outBytes = A5.doiByte(bits);
        String outPath = filePath;
        xulyFile.ghiFile(outPath, outBytes);
        Files.delete(Paths.get(filePath2));
        txtA5PT.setText(outPath);
        JOptionPane.showMessageDialog(this, "Đã giải mã: " + outPath);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_btnA5DecryptionActionPerformed

    private void btnA5EncryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5EncryptionActionPerformed
        try {
        byte[] data = xulyFile.docFile(filePath);
        String keyText = txtA5Key.getText();
        int[] key = new int[keyText.length()];
        for (int i = 0; i < keyText.length(); i++) {
            key[i] = keyText.charAt(i) & 1;
        }
        A5 a5Data = new A5(key);
        A5 a5Name = new A5(key);
        // ---- Mã hóa dữ liệu ----
        int[] bits = A5.doiInt(data);
        int[] enc = a5Data.maHoa(bits.length);
        for (int i = 0; i < bits.length; i++)
            bits[i] ^= enc[i];
        byte[] encryptedBytes = A5.doiByte(bits);
        String tenFile = xulyFile.layTenFile(filePath);
        String tenFile1 = xulyFile.xoaDuoiFile(tenFile);
        String tenMaHoa = A5.maHoaTen(tenFile1, a5Name);
        tenMaHoa = tenMaHoa + duoiFile;
        String folder = Paths.get(filePath).getParent().toString();
        String outPath = folder + "\\" + tenMaHoa;
        xulyFile.ghiFile(outPath, encryptedBytes);
        Files.delete(Paths.get(filePath));
        txtA5CT.setText(outPath);
        JOptionPane.showMessageDialog(this, "Đã mã hóa:\n" + outPath);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnA5EncryptionActionPerformed

    private void btnA5File1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5File1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            filePath2 = chooser.getSelectedFile().getAbsolutePath();
            try {
                // đọc byte[]
                fileData = xulyFile.docFile(filePath2);
                // convert sang Base64 để hiển thị an toàn (mọi loại file)
                String hienThi = Base64.getEncoder().encodeToString(fileData);
                // đưa vào text field
                duoiFile = filePath2.substring(filePath2.lastIndexOf("."));
                txtA5CT.setText(hienThi);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi đọc file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnA5File1ActionPerformed

    private void btnFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFile1ActionPerformed
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            filePath2 = chooser.getSelectedFile().getAbsolutePath();
            try {
                // đọc byte[]
                fileData = xulyFile.docFile(filePath2);
                // convert sang Base64 để hiển thị an toàn (mọi loại file)
                String hienThi = Base64.getEncoder().encodeToString(fileData);
                // đưa vào text field
                txtRC4CT.setText(hienThi);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi đọc file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnFile1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaHoaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaHoaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaHoaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaHoaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaHoaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA5Decryption;
    private javax.swing.JButton btnA5Encryption;
    private javax.swing.JButton btnA5File;
    private javax.swing.JButton btnA5File1;
    private javax.swing.JButton btnDecryp;
    private javax.swing.JButton btnEncryp;
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnFile1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtA5CT;
    private javax.swing.JTextField txtA5Key;
    private javax.swing.JTextArea txtA5PT;
    private javax.swing.JTextArea txtRC4CT;
    private javax.swing.JTextField txtRC4Key;
    private javax.swing.JTextArea txtRC4PT;
    // End of variables declaration//GEN-END:variables
}
